# Generated by Django 4.2.9 on 2024-03-21 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_projectaccess_user_id_project_id'),
        ('repository', '0002_repository_repo_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repository',
            name='project_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='project.project'),
        ),
        migrations.AlterField(
            model_name='repository',
            name='repo_name',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
