# Generated by Django 4.2.9 on 2024-03-24 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0003_alter_repository_project_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repository',
            name='repo_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddConstraint(
            model_name='repository',
            constraint=models.UniqueConstraint(fields=('repo_name', 'project_id'), name='repo_name&project_id'),
        ),
    ]
