# Generated by Django 4.2.9 on 2024-03-24 14:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('repository', '0004_alter_repository_repo_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Star_Repo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('star_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('star_repo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repository.repository')),
            ],
        ),
        migrations.AddConstraint(
            model_name='star_repo',
            constraint=models.UniqueConstraint(fields=('star_by', 'star_repo'), name='repos_starred_by_users'),
        ),
    ]
