# Generated by Django 4.2.9 on 2024-03-26 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0005_star_repo_star_repo_repos_starred_by_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='repository',
            name='is_pinned',
            field=models.BooleanField(default=False),
        ),
    ]
