# Generated by Django 4.2.9 on 2024-03-26 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0006_repository_is_pinned'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='repository',
            name='is_pinned',
        ),
    ]
