# Generated by Django 4.2.9 on 2025-07-27 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0007_remove_repository_is_pinned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repositorycontributor',
            name='repo_id',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='repository.repository'),
        ),
    ]
