# Generated by Django 4.2.4 on 2023-11-27 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_myuser_is_manager_myuser_is_officer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='is_manager',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='is_officer',
        ),
        migrations.AddField(
            model_name='myuser',
            name='is_creator',
            field=models.BooleanField(default=False),
        ),
    ]
