# Generated by Django 4.2.9 on 2024-02-19 06:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_alter_projectaccess_project_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectaccess',
            name='project_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.project'),
        ),
    ]
