# Generated by Django 4.2.9 on 2024-02-19 07:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_alter_projectaccess_project_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectaccess',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
