# Generated by Django 4.2.9 on 2024-02-23 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_projectaccess_created_at'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='projectaccess',
            constraint=models.UniqueConstraint(fields=('user_id', 'project_id'), name='user_id&project_id'),
        ),
    ]
