# Generated by Django 4.2.9 on 2025-07-27 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_projectaccess_user_id_project_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectaccess',
            name='project_id',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='project.project'),
        ),
    ]
